/* EE422C Assignment #2 submission by
 * Colby Janecka
 * CDJ2326
 */

package assignment2;

class Code {

    //Code class instance variables:
    char [] charArray = new char[3];

    // Default Code constructor
    Code(){
    }

    //Code constructor used to store code as character array
    Code(String c){
        charArray = c.toCharArray();
    }

    // codeAsString returns a string with the same characters found in the code's charArray
    String codeAsString(){
        return(new String(charArray));
    }

    // getRandomCode sets the charArray to random values, generated by SecretCodeGenerator class
    void getRandomCode(){
        charArray = SecretCodeGenerator.getInstance().getNewSecretCode().toCharArray();
    }

}
